name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # For multi-platform builds
      # https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: Initialize
        id: init
        run: |
          # Determine whether to push to Docker Hub based on the event type
          case "${{ github.event_name }}" in
            push)
              DOCKER_PUSH=true ;;
            *)
              DOCKER_PUSH=false ;;
          esac

          # Map git ref branch or tag name to Docker tag version
          case "${{ github.ref }}" in
            # Do not push upstream branches and tags to Docker Hub
            refs/heads/upstream/*|refs/tags/upstream/*)
              DOCKER_PUSH=false ;;

            # Do not push pull request branches
            refs/pulls/*)
              DOCKER_PUSH=false ;;

            refs/heads/master)
              DOCKER_TAG=latest ;;
            refs/heads/*|refs/tags/*)
              DOCKER_TAG="$(echo "$GITHUB_REF" | cut -d / -f 3- | \
                sed -e 's,/,-,g')" ;;
          esac

          # Record git source and revision
          GIT_SOURCE=$(git config --get remote.origin.url)
          GIT_REVISION=$(git rev-parse HEAD)$(git diff --quiet || echo "-dirty")

          echo ::set-output name=docker_push::$DOCKER_PUSH
          echo ::set-output name=docker_repo::whoi/$(basename "${{ github.repository }}")
          echo ::set-output name=docker_tag::$DOCKER_TAG
          echo ::set-output name=docker_platforms::linux/amd64,linux/arm64
          echo ::set-output name=git_source::$GIT_SOURCE
          echo ::set-output name=git_revision::$GIT_REVISION

      - name: Log into registry
        if: steps.init.outputs.docker_push == 'true'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build the Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: ${{ steps.init.outputs.docker_platforms }}
          load: true
          # This tag matches what is found in the docker-compose.yml file
          # so that we can run the tests.
          tags: oceandatatools/sealog-server
          build-args: |
            GIT_SOURCE=${{ steps.init.outputs.git_source }}
            GIT_REVISION=${{ steps.init.outputs.git_revision }}

      - name: Run test suite
        run: docker-compose run sealog-server npm test

      - name: Run server
        run: |
          docker-compose up -d
          sleep 10
          curl http://localhost:8000/sealog-server > /tmp/banner.txt
          grep "Welcome to sealog-server\!" /tmp/banner.txt
          docker-compose down

      - name: Push to registry
        if: steps.init.outputs.docker_push == 'true'
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: ${{ steps.init.outputs.docker_platforms }}
          push: true
          tags: ${{ steps.init.outputs.docker_repo }}:${{ steps.init.outputs.docker_tag }}
          build-args: |
            GIT_SOURCE=${{ steps.init.outputs.git_source }}
            GIT_REVISION=${{ steps.init.outputs.git_revision }}
